### ISSUE TITLE
java.lang.OutOfMemoryError: PermGen space

### ISSUE THREAD

**Issue by martinschaef** [jandom-devel/Jandom#11]
Just checked out the project and ran sbt run but it crashes after a while with an exception (see below). I have  scala-2.10.4 and jdk1.7.0_45.jdk in my path.

[info] Done updating.
[info] Compiling 141 Scala sources and 4 Java sources to /Users/schaef/test/Jandom/core/target/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.6. Compiling...
sbt appears to be exiting abnormally.
  The log file for this session is at /var/folders/bb/1rkw83wd0vvfh7ll5qy0qrdc0000gn/T/sbt5444096062645689383.log
java.lang.OutOfMemoryError: PermGen space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
	at sbt.Execute.next$1(Execute.scala:83)
	at sbt.Execute.processAll(Execute.scala:86)
	at sbt.Execute.runKeep(Execute.scala:66)

**Comment by amato-gianluca** [comment]
I don't think this error is related to Jandom: sbt crashes while compiling `compiler-interface` which is an internal component of sbt itself. I don't know why this happens to you (it can be the PC you are using has a limited amount of RAM?). In this StackOverflow article you may find several ideas how to avoid the PermGen error:

http://stackoverflow.com/questions/8331135/how-to-prevent-java-lang-outofmemoryerror-permgen-space-at-scala-compilation

It seems to me that the most valuable suggestions are:
1) use Java 8, or
2) add a line `-J-XX:MaxPermSize=1G` to the file `.sbtopts` in the Jandom's main directory.

Please, let us know if you are able to proceed further.

**Comment by amato-gianluca** [comment]
Another suggestion. The version of Scala you have installed has no impact on the compilation process, since sbt automatically downloads the version of Scala which is required by Jandom (Scala 2.11.6). Also the version of sbt you have installed is mostly ininfluent, since it is essentially a launcher which downloads the correct version from the net. However, if the launcher is too old, this download may fail. I would suggest you to install the sbt package directly from the developer's website, following the instructions here:

http://www.scala-sbt.org/0.13/tutorial/Setup.html
